version: '3.8'

services:
  ai-image-analyzer:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./images:/app/images:ro  # Mount your image directory (read-only)
      - ./results:/app/results   # Mount results directory
    environment:
      - FLASK_ENV=production
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Optional: SSL certificates
    depends_on:
      - ai-image-analyzer
    restart: unless-stopped

volumes:
  ollama_data:
