name: ai-image-analyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - flask=3.1.1
  - pillow=11.3.0
  - requests=2.32.4
  - psutil>=5.9.0
  - pip
  - pip:
    - flask-socketio==5.5.1
    - flask-cors==6.0.1
    - google-genai>=0.8.0
    - piexif>=1.1.3
    - python-dotenv==1.1.1
    - eventlet>=0.35.0
